# Generated by Django 2.2.5 on 2019-10-20 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20191016_0032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
